# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-13 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant_registrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Assi. Registrar', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('hostel', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Computer Center', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('department', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Finance', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gymkhana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gymkhana', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('department', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Library', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='OnlineCC Manager', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stud_Faculty_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_update_time', models.DateTimeField(blank=True, null=True)),
                ('faculty_approval', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('faculty_remarks', models.CharField(blank=True, max_length=1000)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('roll_no', models.IntegerField(default=0)),
                ('hostel', models.CharField(blank=True, max_length=250)),
                ('department', models.CharField(blank=True, max_length=250)),
                ('hostel_update_time', models.DateTimeField(blank=True, null=True)),
                ('hostel_dues', models.BooleanField(default=False)),
                ('hostel_remarks', models.CharField(blank=True, max_length=1000)),
                ('gymkhana_update_time', models.DateTimeField(blank=True, null=True)),
                ('gymkhana_dues', models.BooleanField(default=False)),
                ('gymkhana_remarks', models.CharField(blank=True, max_length=1000)),
                ('library_update_time', models.DateTimeField(blank=True, null=True)),
                ('library_dues', models.BooleanField(default=False)),
                ('library_remarks', models.CharField(blank=True, max_length=1000)),
                ('cc_update_time', models.DateTimeField(blank=True, null=True)),
                ('cc_dues', models.BooleanField(default=False)),
                ('cc_remarks', models.CharField(blank=True, max_length=1000)),
                ('faculty_update_time', models.DateTimeField(blank=True, null=True)),
                ('faculty_dues', models.BooleanField(default=False)),
                ('faculty_remarks', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitThesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Thesis Manager', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('hostel', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='stud_faculty_status',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
    ]
