# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-13 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='faculty_dues',
            new_name='all_dues',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='faculty_remarks',
            new_name='all_remarks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='faculty_update_time',
            new_name='all_update_time',
        ),
    ]
