# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-14 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180414_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Account', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('department', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
    ]
