# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-15 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stud_lab_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='all_dues',
            new_name='finance_dues',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='all_remarks',
            new_name='finance_remarks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='all_update_time',
            new_name='finance_update_time',
        ),
        migrations.AddField(
            model_name='student',
            name='hod_dues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='hod_remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='hod_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
