# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-17 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180417_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='hostel',
            field=models.CharField(blank=True, choices=[('Siang', 'Siang'), ('Kapili', 'Kapili'), ('Dibang', 'Dibang'), ('Lohit', 'Lohit'), ('Brahmaputra', 'Brahmaputra'), ('Umiam', 'Umiam'), ('Dihing', 'Dihing'), ('Manas', 'Manas'), ('Kameng', 'Kameng'), ('Barak', 'Barak'), ('Dhansiri', 'Dhansiri'), ('Subhansiri', 'Subhansiri'), ('Married Scholars', 'Married Scholars')], max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.CharField(blank=True, choices=[('Siang', 'Siang'), ('Kapili', 'Kapili'), ('Dibang', 'Dibang'), ('Lohit', 'Lohit'), ('Brahmaputra', 'Brahmaputra'), ('Umiam', 'Umiam'), ('Dihing', 'Dihing'), ('Manas', 'Manas'), ('Kameng', 'Kameng'), ('Barak', 'Barak'), ('Dhansiri', 'Dhansiri'), ('Subhansiri', 'Subhansiri'), ('Married Scholars', 'Married Scholars')], max_length=250),
        ),
        migrations.AlterField(
            model_name='warden',
            name='hostel',
            field=models.CharField(blank=True, choices=[('Siang', 'Siang'), ('Kapili', 'Kapili'), ('Dibang', 'Dibang'), ('Lohit', 'Lohit'), ('Brahmaputra', 'Brahmaputra'), ('Umiam', 'Umiam'), ('Dihing', 'Dihing'), ('Manas', 'Manas'), ('Kameng', 'Kameng'), ('Barak', 'Barak'), ('Dhansiri', 'Dhansiri'), ('Subhansiri', 'Subhansiri'), ('Married Scholars', 'Married Scholars')], max_length=250),
        ),
    ]
