# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180417_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='webmail',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
