# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-24 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180418_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.CharField(choices=[('B.Tech.', 'B.Tech.'), ('B.Des.', 'B.Des.'), ('M.Tech.', 'M.Tech.'), ('M.Des.', 'M.Des.'), ('Ph.D.', 'Ph.D.'), ('M.Sc.', 'M.Sc.'), ('M.A.', 'M.A.'), ('MSR', 'MSR')], default='B.Tech.', max_length=250),
        ),
    ]
