# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-24 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_student_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_lab_status',
            name='lab_dues',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cc_dues',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='finance_dues',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gymkhana_dues',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hod_dues',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel_dues',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='library_dues',
            field=models.BooleanField(default=True),
        ),
    ]
